# Generated by Django 3.2.5 on 2021-07-30 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rangos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pago_por_hora', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Policias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('nombre_Discord', models.CharField(max_length=100)),
                ('nombre_Steam', models.CharField(blank=True, max_length=100)),
                ('fecha_Iniciado', models.DateTimeField()),
                ('rango', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pfaFichaje.rangos')),
            ],
        ),
        migrations.CreateModel(
            name='Fichajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_Entrada', models.TimeField()),
                ('fecha_Salida', models.TimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Abierto', 'Abierto'), ('Cerrado', 'Cerrado')], default='Abierto', max_length=30)),
                ('policia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pfaFichaje.policias')),
            ],
        ),
        migrations.CreateModel(
            name='CargaHorarias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dinero_Extra', models.IntegerField()),
                ('policia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pfaFichaje.policias')),
            ],
        ),
        migrations.CreateModel(
            name='InfoTotal',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pfaFichaje.cargahorarias',),
        ),
    ]
