# Generated by Django 3.2.5 on 2021-07-31 00:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pfaFichaje', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargahorarias',
            name='horas_totales',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
