# Generated by Django 3.2.5 on 2021-08-11 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfaFichaje', '0002_cargahorarias_horas_totales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichajes',
            name='policia',
        ),
        migrations.DeleteModel(
            name='InfoTotal',
        ),
        migrations.DeleteModel(
            name='Fichajes',
        ),
    ]
