# Generated by Django 3.2.5 on 2021-08-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfaFichaje', '0003_auto_20210811_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargahorarias',
            name='dinero_Extra',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='policias',
            name='apellido',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='policias',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='policias',
            name='nombre_Discord',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rangos',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
