# Generated by Django 3.2.5 on 2021-08-15 02:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pfaFichaje', '0004_auto_20210814_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policias',
            name='fecha_Iniciado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
