# Generated by Django 3.2.5 on 2021-08-19 12:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pfaFichaje', '0005_alter_policias_fecha_iniciado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargahorarias',
            name='fecha_Carga',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
