# Generated by Django 3.2.5 on 2021-08-19 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfaFichaje', '0006_cargahorarias_fecha_carga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargahorarias',
            name='fecha_Carga',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
